name: autotools CI

on:
  push:
    # branches: [ "master" ]
  pull_request:
    # branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install boost
      run: >
        sudo apt -y update &&
        sudo apt install -y libboost-dev

    - name: bootstrap
      run: ./bootstrap

    - name: configure
      run: >
        mkdir _build &&
        cd _build &&
        ../configure

    - name: make
      run: >
        cd _build &&
        make -j2
